### ISSUE TITLE
"'nosidebar': True" leads to protruded (extremely misaligned) footer

### ISSUE THREAD

**Issue by andrei-korshikov** [sphinx-doc/alabaster#209]
**Screenshot:**
![image](https://github.com/sphinx-doc/alabaster/assets/15959858/ca0162cd-b77a-4d0c-8f83-acee1f7774e8)

**Workaround:**
```css
div.footer {
    /* dirty hack for misaligned footer if 'nosidebar' is True */
    width: 700px;
}
```

**Expected behavior:**
![image](https://github.com/sphinx-doc/alabaster/assets/15959858/a79fdd86-d943-4fe8-9665-454384fe7d69)
