### ISSUE TITLE
Float the navigation panel when scrolling

### ISSUE THREAD

**Issue by numberoverzero** [sphinx-doc/alabaster#44]
I've had a few pages get long, where having the navigation scroll with the content would make jumping around the docs much more comfortable.

What about something like the Bootstrap docs navigation sidebar?  [There's a good breakdown here](http://www.codingeverything.com/2014/02/BootstrapDocsSideBar.html) that builds the behavior in layers.

Even without attaching a scrollspy to highlight the current location, simply fixing the navigation to scroll with the content would be a nice enhancement.

**Comment by numberoverzero** [comment]
The basic sphinx styling needs to be overridden a bit here, since `margin-left: -100%` messes with a fixed position.

I've been testing the following which breaks on mobile:

```css
div.sphinxsidebar {
    /* added  */
    position: fixed;

    /* Existing style */
    float: left;
    width: 230px;
    font-size: 90%;
    /* removed */
    /* margin-left: -100%; */
}
```
---

With respect to mobile, I'd argue the nav shouldn't wrap to the bottom of the page anyway.  Testing the [bootstrap docs](http://getbootstrap.com/css) they don't render the navigation at all under 992 px. which only works because they have the top nav.

What about a dropdown button with the top-level headings only for small screens, hiding the fixed sidebar?
